version: "3.3"
services:
  remotedev_new:
    build: .
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - user-data:/home/developer
    - /root:/developer/root
    - lxqt-share:/usr/share/lxqt
    ports:
    - "6081:80"
    environment:
    - USER=developer
    - VNC_PASSWORD=Admin32#
    - RESOLUTION=1920x1080
    privileged: true

volumes:
  user-data:
  lxqt-share:

networks:
  default:
    external:
      name: cp-all-in-one_default
