remotedev: 
  build: .
  restart: unless-stopped
  volumes:
  - /dev/shm:/dev/shm
  - /var/run/docker.sock:/var/run/docker.sock
  - $PWD:/app
  #- ./ubuntu-desktop-lxqt-vnc/ssl:/etc/nginx/ssl
  ports:
  - "6080:80"
  environment:
  - USER=xma
  - PASSWORD=mypassword
  - RESOLUTION=1920x1080
