remotedev:
    build: .
    restart: unless-stopped
    volumes:
    - /dev/shm:/dev/shm
    - ~:/home
    #- ./ubuntu-desktop-lxqt-vnc/ssl:/etc/nginx/ssl
    ports:
    - "127.0.0.1:6080:80"
    environment:
    - USER=xma
    - PASSWORD=mypassword